### PR TITLE
Retry on HTTP 50x errors

### LINKED ISSUE #601: Remote IO should retry certain error codes
Storage services like S3 will return responses with an HTTP 503 error when the number of requests being served exceeds its capacity.  We can hit this error when, e.g., reading many parquet files through cudf (quickly):

```python
  File "parquet.pyx", line 324, in pylibcudf.io.parquet.read_parquet
RuntimeError: curl_easy_perform() error near /opt/conda/conda-bld/work/cpp/src/remote_handle.cpp:255(The requested URL returned error: 503)
```

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html as the default retry policies of boto3 and [this article](https://learn.microsoft.com/en-us/azure/architecture/best-practices/transient-faults) has some general background.

I should be able to take a look at this today. We'll want to retry 429 and 503 codes, and possibly the other 50x codes too.

### PR DESCRIPTION
**Pull request by TomAugspurger**
This updates our remote IO HTTP handler to check the status code of the response. If we get a 50x error, we'll retry up to some limit.

Closes #601

### CODE REVIEW

File: cpp/src/shim/libcurl.cpp [hunk 1]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
 void CurlHandle::perform()
 {
-  // Perform the curl operation and check for errors.
-  CURLcode err = curl_easy_perform(handle());
-  if (err != CURLE_OK) {
-    std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
+  CURLcode err;
+  int http_code   = 0;
+  int retry_count = 0;
+  int max_retries = 5;
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:122]: This should be a configurable limit.

File: cpp/src/shim/libcurl.cpp [hunk 2]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
     std::stringstream ss;
-    ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
-    if (msg.empty()) {
-      ss << "(" << curl_easy_strerror(err) << ")";
+
+    CURLcode err = curl_easy_perform(handle());
+    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);
+
+    // Check if we should retry based on HTTP status code
+    if (http_code == 500 || http_code == 502 || http_code == 503 || http_code == 504) {
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:131]: Should the list of codes to retry be configurable?

Should 429 be in the list of defaults? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 (Too Many Requests). This commonly includes a Retry-After header telling you when to try again.

File: cpp/src/shim/libcurl.cpp [hunk 3]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+      // Retry only if one of the specified status codes is returned
+      retry_count++;
+      ss << "Retrying (" << retry_count << "/" << max_retries << ") due to HTTP " << http_code
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:134]: Move this to an `else` branch below L136, otherwise we'll print that we're retrying again right before printing Max retries reached.

File: cpp/src/shim/libcurl.cpp [hunk 4]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+         << std::endl;
+      if (retry_count >= max_retries) {
+        ss << "Max retries reached. Exiting." << std::endl;
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:137]: "Exiting" isn't really appropriate here.

File: cpp/src/shim/libcurl.cpp [hunk 5]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+    } else if (err != CURLE_OK) {
+      std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
+      ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
+      if (msg.empty()) {
+        ss << "(" << curl_easy_strerror(err) << ")";
+      } else {
+        ss << "(" << msg << ")";
+      }
+      throw std::runtime_error(ss.str());
     } else {
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:150]: This is unchanged from before, just moved after the HTTP status code check. Thinks like an overflow error in the callback handler might end up here and need to bubble up immediately.

File: python/kvikio/kvikio/utils.py [hunk 6]
```diff
@@ -41,6 +40,8 @@ def __init__(
         root_path: str | pathlib.Path,
         range_support: bool = True,
         max_lifetime: int = 120,
+        handler: type[BaseHTTPRequestHandler] | None = None,
```
Comment (TomAugspurger) [inline python/kvikio/kvikio/utils.py:43]: Not sure how much it matters, but the changes to the public API here *should* be backwards compatible.

We just need a way to inject a custom HTTP handler here, so that we can control when a 500 is returned.

File: cpp/src/shim/libcurl.cpp [hunk 7]
```diff
@@ -116,19 +116,43 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
-      ss << "(" << msg << ")";
+      // No retry needed
+      break;
     }
-    throw std::runtime_error(ss.str());
-  }
+
+  } while (retry_count < max_retries);
```
Comment (TomAugspurger) [inline cpp/src/shim/libcurl.cpp:155]: This should probably be more sophisticated. Exponential backoff, jitter, ...

File: cpp/doxygen/main_page.md [hunk 8]
```diff
@@ -111,6 +111,17 @@ KvikIO might have to use intermediate host buffers (one per thread) when copying
 
 This setting can also be controlled by `defaults::bounce_buffer_size()` and `defaults::bounce_buffer_size_reset()`.
 
+#### Number of HTTP Retries
+
+When the HTTP server returns a response indicating a failure (status code of
+`500`, `502`, `503` or `504`) KviIO will retry up to a maximum number of
+attempts.
+
+Set the environment variable ``KVIKIO_MAX_ATTEMPTS`` to the number of attempts
```
Comment (bdice) [inline cpp/doxygen/main_page.md:120]: Markdown just needs one backtick (rST needs two).
```suggestion
Set the environment variable `KVIKIO_MAX_ATTEMPTS` to the number of attempts
```

File: cpp/include/kvikio/defaults.hpp [hunk 9]
```diff
@@ -258,6 +259,23 @@ class defaults {
...
+   * `KVIKIO_MAX_ATTEMPTS` environment variable. If not set, the value is 3.
+   *
+   * @return The maximum number of remote IO reads to attempt before raising an error.
+   */
+  [[nodiscard]] static std::size_t max_attempts();
+
+  /**
+   * @brief Reset the maximum number of attempts per remote IO read.
+   *
+   * @param attempts The The maximum number of attempts to try before raising an error.
```
Comment (bdice) [inline cpp/include/kvikio/defaults.hpp:276]:
```suggestion
   * @param attempts The maximum number of attempts to try before raising an error.
```

File: cpp/src/shim/libcurl.cpp (hunk 2 above)
Comment (bdice) [reply cpp/src/shim/libcurl.cpp:134]: Yes, and possibly 400 Bad Request? (Sometimes the issue is corruption in the request sent from client to server)

File: cpp/src/shim/libcurl.cpp [hunk 10]
```diff
@@ -116,19 +118,48 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);
+
+    // Check if we should retry based on HTTP status code
+    if (http_code == 500 || http_code == 502 || http_code == 503 || http_code == 504) {
+      // Retry only if one of the specified status codes is returned
+      ss << "HTTP " << http_code << std::endl;
+      if (attempt_count == max_attempts) {
+        ss << "Max attempts reached." << std::endl;
+        throw std::runtime_error(ss.str());
+        break;
```
Comment (madsbk) [inline cpp/src/shim/libcurl.cpp:140]:
```suggestion
```

File: python/kvikio/tests/test_http_io.py [hunk 11]
```diff
@@ -100,3 +147,40 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+    a.tofile(tmpdir / "a")
+
+    error_counter = ErrorCounter()
+
+    with LocalHttpServer(
+        tmpdir,
+        max_lifetime=60,
+        handler=HTTP500Handler,
+        handler_options={"error_counter": error_counter},
+    ) as server:
```
Comment (madsbk) [inline python/kvikio/tests/test_http_io.py:163]:
```suggestion
    with LocalHttpServer(
        tmpdir,
        max_lifetime=60,
        handler=HTTP500Handler,
        handler_options={"error_counter":  ErrorCounter()},
    ) as server:
```

Comment (madsbk) [reply python/kvikio/tests/test_http_io.py:163]: Or will this not work because `LocalHttpServer` clear or deep copy the `handler_options` dict?

**Review by madsbk — COMMENTED** [review]
Looks good @TomAugspurger. 
I agree, it would be good to make code list configurable. Or at least, define it as a constexpr somewhere.

File: cpp/src/defaults.cpp [hunk 12]
```diff
@@ -91,6 +91,25 @@ CompatMode getenv_or(std::string_view env_var_name, CompatMode default_val)
...
 
+template <>
+std::vector<int> getenv_or(std::string_view env_var_name, std::vector<int> default_val)
+{
+  auto* env_val = std::getenv(env_var_name.data());
+  if (env_val == nullptr) { return default_val; }
+  std::vector<int> vect;
+  std::stringstream ss(env_val);
+
+  for (int i; ss >> i;) {
```
Comment (TomAugspurger) [inline cpp/src/defaults.cpp:102]: My lack of C++ experience is showing here, but I could use some help here. To goal here is to parse a string like `"429,500,503"` to a list of integers like `[429, 500, 503]`.

Right now, it seems like exceptions are being swallowed somwhere, at least when accessed through Python:

```
KVIKIO_HTTP_STATUS_CODES="a" python -c 'import kvikio.defaults; print(kvikio.defaults.http_status_codes())'
[]
```

And we aren't handling valid lists properly :/

```
KVIKIO_HTTP_STATUS_CODES="429,500" python -c 'import kvikio.defaults; print(kvikio.defaults.http_status_codes())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/coder/kvikio/python/kvikio/kvikio/defaults.py", line 318, in http_status_codes
    return kvikio._lib.defaults.http_status_codes()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "defaults.pyx", line 89, in kvikio._lib.defaults.http_status_codes
ValueError: Invalid value 429,500
```

File: cpp/src/defaults.cpp [hunk 13]
```diff
@@ -91,6 +91,25 @@ CompatMode getenv_or(std::string_view env_var_name, CompatMode default_val)
...
+    vect.push_back(i);
+    if (ss.peek() == ',' || ss.peek() == ' ') { ss.ignore(); }
+
+    // TODO: this isn't working yet.
+    if (ss.fail()) { throw std::invalid_argument("Invalid value " + std::string(env_val)); }
+  }
+
+  return vect;
+}
+
```
Comment (madsbk) [inline cpp/src/defaults.cpp:112]: Using regex, this would work:

```suggestion
template <>
std::vector<int> getenv_or(std::string_view env_var_name, std::vector<int> default_val)
{
  auto* const env_val = std::getenv(env_var_name.data());
  if (env_val == nullptr) { return default_val; }
  std::string const int_str(env_val);
  if (int_str.empty()) { return default_val; }

  // Ensure `int_str` consists only of integers separated by commas, allowing spaces.
  std::regex const check_pattern(R"(^\s*\d+\s*(\s*,\s*\d+\s*)*$)");
  if (!std::regex_match(int_str, check_pattern)) {
    throw std::invalid_argument(std::string{env_var_name} +
                                ": invalid format, expected comma-separated integers.");
  }

  // Match every integer in `int_str`.
  std::regex const number_pattern(R"(\d+)");

  // For each match, we push_back `std::stoi(match.str())` into `ret`.
  std::vector<int> ret;
  std::transform(std::sregex_iterator(int_str.begin(), int_str.end(), number_pattern),
                 std::sregex_iterator(),
                 std::back_inserter(ret),
                 [](std::smatch const& match) -> int { return std::stoi(match.str()); });
  return ret;
}

```

File: cpp/src/shim/libcurl.cpp (hunk 2 above)
Comment (bdice) [reply cpp/src/shim/libcurl.cpp]: I think your thoughts are good! I'm happy for us to follow your recommendations here. Thanks for doing that research.

File: cpp/src/defaults.cpp (hunk 13 above)
Comment (bdice) [reply cpp/src/defaults.cpp:112]: Maybe we make it even stricter and require the integers to have 3 digits. This might work (untested).
```
std::regex const check_pattern(R"(^\s*\d{3}\s*(\s*,\s*\d{3}\s*)*$)");
```

Comment (TomAugspurger) [reply cpp/src/defaults.cpp:112]: That works perfectly, thanks!

```
KVIKIO_HTTP_STATUS_CODES="429,500,a" python -c 'import kvikio.defaults; print(kvikio.defaults.http_status_codes())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/coder/kvikio/python/kvikio/kvikio/defaults.py", line 318, in http_status_codes
    return kvikio._lib.defaults.http_status_codes()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "defaults.pyx", line 89, in kvikio._lib.defaults.http_status_codes
ValueError: KVIKIO_HTTP_STATUS_CODES: invalid format, expected comma-separated integers.
```

I'm going to write up a quick test for this in C++ before pushing.

Comment (TomAugspurger) [reply cpp/src/defaults.cpp]: Well, I haven't figured out how to run the C++ tests locally yet :/ I'll come back to the later today.

**Comment by TomAugspurger** [comment]
Apologies for the force-commit. The commits made from my devcontainer last week weren't being signed for some reason.

File: cpp/src/defaults.cpp (hunk 13 above)
Comment (TomAugspurger) [reply cpp/src/defaults.cpp]: Added in https://github.com/rapidsai/kvikio/pull/603/commits/bf33697ba450173ccd76f4de46cc2faf6308c9d2.

**Comment by TomAugspurger** [comment]
The two CI failures appear to be from the 6-hour timeout on the github action: https://github.com/rapidsai/kvikio/actions/runs/13117029669/job/36594707434?pr=603#step:9:1556

```
context canceled
python/kvikio/tests/test_benchmarks.py::test_http_io[cupy] 
Error: The operation was canceled.
```

I assume that's unrelated to the changes here. If possible, it might be best to rerun just those failed jobs?

- https://github.com/rapidsai/kvikio/actions/runs/13117029669/job/36594707434?pr=603
- https://github.com/rapidsai/kvikio/actions/runs/13117029669/job/36594707886?pr=603

**Comment by bdice** [comment]
If there are jobs with hangs, we need to diagnose those offline and not rerun them. Consuming a GPU runner for 6 hours is not good, especially with our limited supply of ARM nodes.

**Comment by TomAugspurger** [comment]
Makes sense. https://github.com/rapidsai/kvikio/actions/runs/13117029669 (from #1465)  also took much longer than normal on these same two matrix entries.

https://github.com/rapidsai/kvikio/actions/runs/13117029669/job/36594707886?pr=603 is one of the slow jobs. That


- 16:23:01 started `Run tests`
- 16:23:53-16:26:25  compiling numcodecs at 
  - something to look into: Why are we compiling numcodecs? See if it can provide a wheel and save us some time.
- 16:27:13 started pytest
- 16:28:05 last successful test finished
- 22:20:06 Run canceled while running `python/kvikio/tests/test_benchmarks.py::test_http_io[cupy]`
- ~1 second ago: I realized my code is almost surely to blame :)

A bit strange it passed on conda though. I'll take a look.

**Comment by TomAugspurger** [comment]
That said, https://github.com/rapidsai/kvikio/actions/runs/13117029669/job/36594707434 (testing https://github.com/rapidsai/kvikio/pull/608) also timed out after 6 hours on the same test, and it was running at around the same time.

That test seems to use the `run_cmd` fixture to run a benchmark in a subprocess. I don't think we have logs to confirm it, but it's almost surely hanging while starting that subprocess or within it. I'll look into adding a timeout mechanism to `run_cmd` (cc @kingcrimsontianyu, just in case your PR hits that timeout again, no need for you to investigate too).

**Comment by TomAugspurger** [comment]
I wish I were more confident, but the hang is probably happening in https://github.com/rapidsai/kvikio/blob/74653a33c30c11bb7c25c84e484bf11913203b71/python/kvikio/tests/conftest.py#L22-L24. We could probably catch most of these by setting a timeout in that `subprocess.call`. However, that's not the easiest to integrate into the rest of that `run_cmd` fixture, since it's using blocking calls to `.send()` and `.recv()` to send test commands and receive results, and those don't have timeout parameters. If we raise a `TimeoutError` there, `run_cmd` would hang on the `.recv()` since the server never writes anything to the pipe.

I'd recommend two things

1. Add pytest-timeout as a test dependency, and ensure that these tests have a timeout.  With small timeouts and added `time.sleep` commands in the `http_io.py` file I've confirmed that pytest-timeout does interrupt the individual tests and the test process finishes.
2. Investigate the cause of the hangs in the first place. I'm like 99% sure that we should be setting [`CURLOPT_TIMEOUT`](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) somewhere in `libcurl.cpp` before we perform any requests. Which means we would need to pick a default and expose that up through to the user as a configuration value / parameter for requests made by kvikio. That should probably be done as a separate PR.

**Comment by TomAugspurger** [comment]
Another failure at https://github.com/rapidsai/kvikio/actions/runs/13141081794/job/36668845969?pr=603#step:9:2120. This at least indicates that the timeout is working :/

I'll try again to reproduce it locally.

**Comment by TomAugspurger** [comment]
Well I'm *unable* to reproduce when building kvikio (with or without debug symbols). In the container running

```
apt update && apt install gdb sccache libcurl4-openssl-dev cmake

python -m pip install rapids-build-backend scikit-build-core ninja cython \
	cupy-cuda12x numpy dask rangehttpserver

./build.sh libkvikio kvikio
LD_LIBRARY_PATH=cpp/build/:$LD_LIBRARY_PATH \
	python python/kvikio/kvikio/benchmarks/http_io.py --api numpy
```

prints the normal benchmark output, no issues.


One thing I noticed, in the `wheel-cpp-build` job we find [curl@8.5.0](https://github.com/rapidsai/kvikio/actions/runs/13141081794/job/36668199761?pr=603#step:10:130)

```
  -- curl version=[8.5.0-DEV]
```

In the `wheel-python-build` stage we find [7.6.0](https://github.com/rapidsai/kvikio/actions/runs/13141081794/job/36668504937?pr=603#step:10:167)

```
  -- Found CURL: /usr/lib64/libcurl.so (found version "7.61.1")
```

Is that worrysome to anyone who knows this stuff better than I do (cc @madsbk)?

**Comment by madsbk** [comment]
> Well I'm _unable_ to reproduce when building kvikio (with or without debug symbols). In the container running
> 
> ```
> apt update && apt install gdb sccache libcurl4-openssl-dev cmake
> 
> python -m pip install rapids-build-backend scikit-build-core ninja cython \
> 	cupy-cuda12x numpy dask rangehttpserver
> 
> ./build.sh libkvikio kvikio
> LD_LIBRARY_PATH=cpp/build/:$LD_LIBRARY_PATH \
> 	python python/kvikio/kvikio/benchmarks/http_io.py --api numpy
> ```
> 
> prints the normal benchmark output, no issues.
> 
> One thing I noticed, in the `wheel-cpp-build` job we find [curl@8.5.0](https://github.com/rapidsai/kvikio/actions/runs/13141081794/job/36668199761?pr=603#step:10:130)
> 
> ```
>   -- curl version=[8.5.0-DEV]
> ```
> 
> In the `wheel-python-build` stage we find [7.6.0](https://github.com/rapidsai/kvikio/actions/runs/13141081794/job/36668504937?pr=603#step:10:167)
> 
> ```
>   -- Found CURL: /usr/lib64/libcurl.so (found version "7.61.1")
> ```
> 
> Is that worrysome to anyone who knows this stuff better than I do (cc @madsbk)?

That is wrong! We should be using v8.5.0+, I am surprised that CMake would even accept 7.61.1?!?

AFAIKT we are using v8.5.0 for the `wheel-python-build`: https://github.com/rapidsai/kvikio/blob/branch-25.02/cpp/cmake/thirdparty/get_libcurl.cmake#L31. 

@bdice do you know what is going on?

**Comment by TomAugspurger** [comment]
My best guess here is that the wheel build is picking up libcurl from the environment, rather than using `get_libcurl.cmake`.

The version in the container `rapidsai/ci-wheel:cuda12.8.0-rockylinux8-py3.10` happens to be 7.6.1:

```
docker run -it --rm rapidsai/ci-wheel:cuda12.8.0-rockylinux8-py3.10 strings /usr/lib64/libcurl.so | grep -i '^libcurl'
libcurl.so.4
libcurl/H
libcurl is now using a weak random seed!
libcurl.so.4.5.0.minimal-7.61.1-34.el8_10.3.x86_64.debug
```

I'm wondering / guessing that if we update the version of curl inside that container, things will work as expected. Is that a sensible step though, or should we be updating the container itself, so that any of our projects using it will get the newer curl?

**Comment by madsbk** [comment]
> My best guess here is that the wheel build is picking up libcurl from the environment, rather than using `get_libcurl.cmake`.

I guess you are right, but we specify [`CURL 8.5.0`](https://github.com/rapidsai/kvikio/blob/b5758ec8483682cb7e50e4b7a4fb3b139b368534/cpp/cmake/thirdparty/get_libcurl.cmake#L25) explicitly.

> I'm wondering / guessing that if we update the version of curl inside that container, things will work as expected. Is that a sensible step though, or should we be updating the container itself, so that any of our projects using it will get the newer curl?

But users expect KvikIO wheels to work even if they have a old libcurl installed on their system.

File: python/kvikio/tests/test_http_io.py [hunk 14]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+        tmpdir,
+        max_lifetime=60,
+        handler=HTTP500Handler,
+        handler_options={"error_counter": ErrorCounter()},
+    ) as server:
+        http_server = server.url
+        with kvikio.defaults.set_http_status_codes([429]):
+            # this raises on the first 503 error, since it's not in the list.
+            assert kvikio.defaults.http_status_codes() == [429]
+            with pytest.raises(RuntimeError, match="503"):
```
Comment (TomAugspurger) [inline python/kvikio/tests/test_http_io.py:206]: As I start to think about #613 (timeouts) I'm wondering if kvikio should raise this a specialized exception type rather than a generic RuntimeError.

Doing a full exception hierarchy like [httpx](https://www.python-httpx.org/exceptions/#exception-classes) may be a bit much, but at least differentiating between a completed HTTP request with a 500 status code and a timeout is probably worthwhile.

Comment (madsbk) [reply python/kvikio/tests/test_http_io.py:206]: I think that would be a great idea. The current exception origination is very basic.

**Comment by TomAugspurger** [comment]
Some good news / bad news:

Good news: I was able to build kvikio with debug symbols.
Bad news: the segfault goes away :(
Maybe good news: the variables look weird?

Some notes on how I did that:

Prep by enabling debug mode + hacking some paths

<details>

```diff
diff --git a/VERSION b/VERSION
index 72eefaf..bc53271 100644
--- a/VERSION
+++ b/VERSION
@@ -1 +1 @@
-25.02.00
+25.02.00a40
\ No newline at end of file
diff --git a/ci/build_wheel_cpp.sh b/ci/build_wheel_cpp.sh
index ca27717..4b84eca 100755
--- a/ci/build_wheel_cpp.sh
+++ b/ci/build_wheel_cpp.sh
@@ -25,7 +25,7 @@ python -m pip install \
 # 0 really means "add --no-build-isolation" (ref: https://github.com/pypa/pip/issues/5735)
 export PIP_NO_BUILD_ISOLATION=0
 
-export SKBUILD_CMAKE_ARGS="-DUSE_NVCOMP_RUNTIME_WHEEL=ON"
+export SKBUILD_CMAKE_ARGS="-DUSE_NVCOMP_RUNTIME_WHEEL=ON -DSKBUILD_CMAKE_BUILD_TYPE=Debug"
 ./ci/build_wheel.sh "${package_name}" "${package_dir}"
 
 RAPIDS_PY_CUDA_SUFFIX="$(rapids-wheel-ctk-name-gen ${RAPIDS_CUDA_VERSION})"
diff --git a/ci/build_wheel_python.sh b/ci/build_wheel_python.sh
index 088e8e8..8ae33f0 100755
--- a/ci/build_wheel_python.sh
+++ b/ci/build_wheel_python.sh
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2023-2024, NVIDIA CORPORATION.
+#b Copyright (c) 2023-2024, NVIDIA CORPORATION.
 
 set -euo pipefail
 
@@ -12,10 +12,13 @@ RAPIDS_PY_CUDA_SUFFIX="$(rapids-wheel-ctk-name-gen ${RAPIDS_CUDA_VERSION})"
 #
 # Using env variable PIP_CONSTRAINT is necessary to ensure the constraints
 # are used when creating the isolated build environment
-RAPIDS_PY_WHEEL_NAME="libkvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 cpp /tmp/libkvikio_dist
-echo "libkvikio-${RAPIDS_PY_CUDA_SUFFIX} @ file://$(echo /tmp/libkvikio_dist/libkvikio_*.whl)" > /tmp/constraints.txt
+# RAPIDS_PY_WHEEL_NAME="libkvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 cpp /tmp/libkvikio_dist
+RAPIDS_PY_WHEEL_NAME="libkvikio_${RAPIDS_PY_CUDA_SUFFIX}"
+echo "libkvikio-${RAPIDS_PY_CUDA_SUFFIX} @ file:///repo/$(echo python/libkvikio/final_dist/libkvikio_*.whl)" > /tmp/constraints.txt
 export PIP_CONSTRAINT="/tmp/constraints.txt"
 
+export SKBUILD_INSTALL_STRIP=false
+export SKBUILD_CMAKE_BUILD_TYPE=Debug
 export SKBUILD_CMAKE_ARGS="-DUSE_NVCOMP_RUNTIME_WHEEL=ON"
 ./ci/build_wheel.sh "${package_name}" "${package_dir}"
 
diff --git a/ci/test_wheel.sh b/ci/test_wheel.sh
index 46ae5cb..801db35 100755
--- a/ci/test_wheel.sh
+++ b/ci/test_wheel.sh
@@ -5,13 +5,13 @@ set -eou pipefail
 
 RAPIDS_PY_CUDA_SUFFIX="$(rapids-wheel-ctk-name-gen ${RAPIDS_CUDA_VERSION})"
 
-# Download and install the libkvikio and kvikio wheels built in the previous step
-RAPIDS_PY_WHEEL_NAME="libkvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 cpp ./dist
-RAPIDS_PY_WHEEL_NAME="kvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 python ./dist
+# # Download and install the libkvikio and kvikio wheels built in the previous step
+# RAPIDS_PY_WHEEL_NAME="libkvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 cpp ./dist
+# RAPIDS_PY_WHEEL_NAME="kvikio_${RAPIDS_PY_CUDA_SUFFIX}" rapids-download-wheels-from-s3 python ./dist
 
 python -m pip install -v \
-  "$(echo ./dist/libkvikio_${RAPIDS_PY_CUDA_SUFFIX}*.whl)" \
-  "$(echo ./dist/kvikio_${RAPIDS_PY_CUDA_SUFFIX}*.whl)[test]"
+  "$(echo ./python/libkvikio/final_dist/libkvikio_${RAPIDS_PY_CUDA_SUFFIX}*.whl)" \
+  "$(echo ./python/kvikio/final_dist/kvikio_${RAPIDS_PY_CUDA_SUFFIX}*.whl)[test]"
 
 # If running CUDA 11.8 on arm64, we skip tests marked "cufile" since
 # cuFile didn't support arm until 12.4
```

</details>

Build the libkvikio wheel


```
docker run \
  --rm \
  -it \
  --gpus all \
  --pull=always \
  --network=host \
  --volume $PWD:/repo \
  --workdir /repo \
  --cap-add=SYS_PTRACE \
  --security-opt \
  seccomp=unconfined \
  rapidsai/ci-wheel:cuda12.8.0-rockylinux8-py3.12 \
  -- ./ci/build_wheel_cpp.sh
```

Build the kvikio wheel:

```
docker run \
  --rm \
  -it \
  --gpus all \
  --pull=always \
  --network=host \
  --volume $PWD:/repo \
  --workdir /repo \
  --cap-add=SYS_PTRACE \
  --security-opt \
  seccomp=unconfined \
  rapidsai/ci-wheel:cuda12.8.0-rockylinux8-py3.12 \
  -- ./ci/build_wheel_python.sh
```

At this point you can unzip the wheels and confirm that the debug symbols are present

```
$ unzip python/kvikio/final_dist/kvikio_cu12-25.2.0a40-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl -d out/kvikio
$ file out/kvikio/kvikio/_lib/remote_handle.cpython-312-x86_64-linux-gnu.so
out/kvikio/kvikio/_lib/remote_handle.cpython-312-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cda8f42c4e25c2be8cb8e4d3264e8ee6ded3e2f7, with debug_info, not stripped
```

Install the wheels in the test container, run the tests

```
docker run \
  --rm \
  -it \
  --gpus all \
  --pull=always \
  --network=host \
  --volume $PWD:/repo \
  --workdir /repo \
  --cap-add=SYS_PTRACE \
  --security-opt \
  seccomp=unconfined \
 rapidsai/citestwheel:cuda12.8.0-ubuntu24.04-py3.12
```


```
./ci/test_wheel.sh  # just the build section. Can ctrl-c once tests starts
```


Confirm the segfault

```
python python/kvikio/kvikio/benchmarks/http_io.py --api numpy
```

That segfaults without debug symbols, but doesn't with.

I am able to confirm `info locals` works

```
apt update && apt install -y gdb
gdb -ex "break kvikio::CurlHandle::perform" -ex r --args bash python kvikio/kvikio/benchmarks/http_io.py --api numpy

Thread 68 "python" hit Breakpoint 1, kvikio::CurlHandle::perform (this=0x7fff563c2870) at /repo/cpp/src/shim/libcurl.cpp:122
122       int http_code                      = 0;
(gdb) info locals
err = <optimized out>
http_code = 32767
attempt_count = 0
baseDelay = 4096
max_attempts = 6
http_status_codes = std::vector of length -82254199, capacity 8 = {1446782432, 32767, 1, 0, 1446783856, 32767, 1121954688, 32767, 1446782496, 32767, 0, 0, 1446782543, 1, -185053148, 32767, 2, 0, 1446783824, 32767, 1446782560, 32767, 1117363346, 32767, 
  1466005136, 21845, 1446783792, 32767, 1446783824, 32767, 1446783056, 32767, 6, 0, 4096, 0, 1466005136, 21845, 1121954688, 32767, 1446783952, 32767, 1117743026, 32767, 0, 0, 4096, 0, 1460862000, 21845, 1462721824, 21845, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1796992256, 620669526, 0, 0, -141941872, 32767, 0, 0, 1446784192, 32767, 1446784400, 32767, -141941849, 32767, 1446784176, 32767, -143396283, 32767, -141941849, 32767, 1446783120, 32767, 0, 
  0, -1, -1, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, -141941849, 32767, -141941872, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1460862000, 21845, 4096, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1446783072, 32767, 6, 0, 808725808, 13625, 32, 
  48, 1446784512, 32767, 1446784432, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}
```


That `http_status_codes` vector looks weird right? I'm clearly not a C++ expert, but why would the length be negative?


I'll go through that again both with and without my changes to enable debug builds.

**Comment by TomAugspurger** [comment]
With some print debugging, I've narrowed the issue down to checking `http_code` against the `http_status_codes` vector. Get get to that `if` check, but not past it.

```
    // Check if we should retry based on HTTP status code
    if (std::find(http_status_codes.begin(), http_status_codes.end(), http_code) !=
        http_status_codes.end()) {
 ```

Things work fine if I just hardcode the vector of status codes instead of getting the from `kvikio::defaults::http_status_codes()`:

```
  // std::vector<int> http_status_codes = kvikio::defaults::http_status_codes();
  std::vector<int> http_status_codes = {429, 500, 502, 503, 504};
```

Going back to `kvikio::defaults::http_status_codes();`, I put in some more print statements:

```
    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);

    // this `if` check fails. Why? Unroll that to find out:
    for (auto const& code : http_status_codes) {
      std::cout << "code " << code << std::endl;
      
      if (code == http_code) {
        std::cout << "HTTP " << code << " == " << http_code << std::endl;
        break;
      } else {
        std::cout << "HTTP " << code << " != " << http_code << std::endl;
      }
    }
```

And see a bunch of junk comparisions:

```
...
HTTP 1761638770 != 206
code 543236211
HTTP 543236211 != 206
code 1851880563
HTTP 1851880563 != 206
code 1685217636
HTTP 1685217636 != 206
code 37
HTTP 37 != 206
code 0
HTTP 0 != 206
code 429
HTTP 429 != 206
code 500
HTTP 500 != 206
code 502
HTTP 502 != 206
code 503
HTTP 503 != 206
code 504
HTTP 504 != 206
Segmentation fault (core dumped)
```

So there's something is strange with that vector.

File: cpp/include/kvikio/defaults.hpp [hunk 15]
```diff
@@ -57,6 +57,9 @@ namespace detail {
  */
 CompatMode parse_compat_mode_str(std::string_view compat_mode_str);
 
+std::vector<int> parse_http_status_codes(std::string_view nev_var_name,
```
Comment (madsbk) [inline cpp/include/kvikio/defaults.hpp:60]: Would be good with a docstring here

**Review by madsbk — COMMENTED** [review]
I think I fixed the issue, `CURLINFO_RESPONSE_CODE` is a `long` not a `int` :)

**Comment by TomAugspurger** [comment]
Awesome, thanks!

@madsbk should I change the target to branch to `branch-2025.04`?

File: docs/source/runtime_settings.rst [hunk 16]
```diff
@@ -42,3 +42,12 @@ Size of the Bounce Buffer ``KVIKIO_BOUNCE_BUFFER_SIZE``
 KvikIO might have to use intermediate host buffers (one per thread) when copying between files and device memory. Set the environment variable ``KVIKIO_BOUNCE_BUFFER_SIZE`` to the size (in bytes) of these "bounce" buffers. If not set, the default value is 16777216 (16 MiB).
 
 This setting can also be controlled by :py:func:`kvikio.defaults.bounce_buffer_size`, :py:func:`kvikio.defaults.bounce_buffer_size_reset`, and :py:func:`kvikio.defaults.set_bounce_buffer_size`.
+
+HTTP Retries ``KVIKIO_MAX_ATTEMPTS``
```
[the remark this answers is not in the document]
Comment (TomAugspurger) [reply docs/source/runtime_settings.rst:46]: And I'm going to change prefix "max_attempts" with "http" so this will be `KVIKIO_HTTP_MAX_ATTEMPTS`. That makes it clear this only applies to remote IO, and will fit in nicely with `HTTP_STATUS_CODES` and `HTTP_TIMEOUT` when we get to that.

File: python/kvikio/tests/test_http_io.py (hunk 14 above)
Comment (TomAugspurger) [reply python/kvikio/tests/test_http_io.py:206]: Opened https://github.com/rapidsai/kvikio/issues/624 for that.

File: cpp/doxygen/main_page.md [hunk 17]
```diff
@@ -107,10 +107,38 @@ To improve performance of small IO requests, `.pread()` and `.pwrite()` implemen
...
 
 #### Size of the Bounce Buffer (KVIKIO_GDS_THRESHOLD)
-KvikIO might have to use intermediate host buffers (one per thread) when copying between files and device memory. Set the environment variable ``KVIKIO_BOUNCE_BUFFER_SIZE`` to the size (in bytes) of these "bounce" buffers. If not set, the default value is 16777216 (16 MiB).
+KvikIO might have to use intermediate host buffers (one per thread) when copying between files and device memory. Set the environment variable `KVIKIO_BOUNCE_BUFFER_SIZE` to the size (in bytes) of these "bounce" buffers. If not set, the default value is 16777216 (16 MiB).
 
 This setting can also be controlled by `defaults::bounce_buffer_size()` and `defaults::bounce_buffer_size_reset()`.
 
+#### HTTP Retries
+
+The behavior when a remote IO read returns a error can be controlled through the
```
Comment (bdice) [inline cpp/doxygen/main_page.md:116]: I think the rest of this page is using semantic line breaks, not hard-wrapping at a specific width. Could we match? https://sembr.org/

File: cpp/include/kvikio/defaults.hpp [hunk 18]
```diff
@@ -57,6 +57,19 @@ namespace detail {
  */
 CompatMode parse_compat_mode_str(std::string_view compat_mode_str);
 
+/**
+ * @brief Parse a string of comma-separated string of HTTP status.
```
Comment (bdice) [inline cpp/include/kvikio/defaults.hpp:61]:
```suggestion
 * @brief Parse a string of comma-separated string of HTTP status codes.
```

File: cpp/tests/test_defaults.cpp [hunk 19]
```diff
@@ -51,3 +51,25 @@ TEST(Defaults, parse_compat_mode_str)
...
   }
 }
+
+TEST(Defaults, parse_http_status_codes)
+{
+  {
+    std::vector<std::string> inputs{
+      "429,500", "429, 500", " 429,500", "429,  500", "429 ,500", "429,500 "};
+    std::vector<int> expected = {429, 500};
+    // std::string const input = "429,500,501,503";
```
Comment (bdice) [inline cpp/tests/test_defaults.cpp:61]:
```suggestion
```

File: docs/source/runtime_settings.rst [hunk 20]
```diff
@@ -42,3 +42,21 @@ Size of the Bounce Buffer ``KVIKIO_BOUNCE_BUFFER_SIZE``
 KvikIO might have to use intermediate host buffers (one per thread) when copying between files and device memory. Set the environment variable ``KVIKIO_BOUNCE_BUFFER_SIZE`` to the size (in bytes) of these "bounce" buffers. If not set, the default value is 16777216 (16 MiB).
 
 This setting can also be controlled by :py:func:`kvikio.defaults.bounce_buffer_size`, :py:func:`kvikio.defaults.bounce_buffer_size_reset`, and :py:func:`kvikio.defaults.set_bounce_buffer_size`.
+
+#### HTTP Retries
+-----------------
+
+The behavior when a remote IO read returns a error can be controlled through the
```
Comment (bdice) [inline docs/source/runtime_settings.rst:49]: Semantic line breaks here too, please.

File: python/kvikio/kvikio/defaults.py [hunk 21]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
         yield
     finally:
         bounce_buffer_size_reset(old_value)
+
+
+def http_max_attempts() -> int:
+    """Get the maximum number of attempts per remote IO read.
+
+    Read are retried up until ``http_max_attempts`` when the response has certain
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:256]:
```suggestion
    Reads are retried up until ``http_max_attempts`` when the response has certain
```

File: python/kvikio/kvikio/defaults.py [hunk 22]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+    HTTP status codes.
+
+    Set the value using `http_max_atttempts_reset()` or by setting the
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:259]:
```suggestion
    Set the value using `http_max_attempts_reset()` or by setting the
```

File: python/kvikio/kvikio/defaults.py [hunk 23]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+    `KVIKIO_HTTP_MAX_ATTEMPTS` environment variable. If not set, the
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:260]:
```suggestion
    ``KVIKIO_HTTP_MAX_ATTEMPTS`` environment variable. If not set, the
```

File: python/kvikio/kvikio/defaults.py [hunk 24]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+
+    - 429
+    - 500
+    - 502
+    - 503
+    - 504
+
+    Returns
+    -------
+    status_coders : list[int]
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:315]:
```suggestion
    status_codes : list[int]
```

File: python/kvikio/kvikio/defaults.py [hunk 25]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+
+
+@contextlib.contextmanager
+def set_http_status_codes(status_codes: list[int]):
+    """Context for resetting the the maximum number of HTTP attempts.
+
+    Parameters
+    ----------
+    attempts : int
+        The maximum number of attempts to try before raising an error.
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:339]:
```suggestion
    status_codes : list[int]
        The HTTP status codes to retry.
```

File: python/kvikio/kvikio/defaults.py [hunk 26]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+    """
+    kvikio._lib.defaults.http_status_codes_reset(status_codes)
+
+
+@contextlib.contextmanager
+def set_http_status_codes(status_codes: list[int]):
+    """Context for resetting the the maximum number of HTTP attempts.
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:334]:
```suggestion
    """Context for resetting the HTTP status codes to retry.
```

File: python/kvikio/kvikio/defaults.py [hunk 27]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+    ----------
+    attempts : int
+        The maximum number of attempts to try before raising an error.
+    """
+    kvikio._lib.defaults.http_max_attempts_reset(attempts)
+
+
+@contextlib.contextmanager
+def set_http_max_attempts(attempts: int):
+    """Context for resetting the the maximum number of HTTP attempts.
```
Comment (bdice) [inline python/kvikio/kvikio/defaults.py:285]:
```suggestion
    """Context for resetting the maximum number of HTTP attempts.
```

File: python/kvikio/tests/test_defaults.py [hunk 28]
```diff
@@ -84,3 +84,34 @@ def test_bounce_buffer_size():
...
+
+
+def test_http_max_attempts():
+    before = kvikio.defaults.http_max_attempts()
+
+    with kvikio.defaults.set_http_max_attempts(5):
+        assert kvikio.defaults.http_max_attempts() == 5
+        kvikio.defaults.http_max_attempts_reset(4)
+        assert kvikio.defaults.http_max_attempts() == 4
+    assert before == kvikio.defaults.http_max_attempts()
```
Comment (bdice) [inline python/kvikio/tests/test_defaults.py:96]: PyTest's errors are sometimes a bit clearer if you follow the order of `assert actual == expected`.
```suggestion
    assert kvikio.defaults.http_max_attempts() == before
```

File: python/kvikio/tests/test_defaults.py [hunk 29]
```diff
@@ -84,3 +84,34 @@ def test_bounce_buffer_size():
...
+
+
+def test_http_status_codes():
+    before = kvikio.defaults.http_status_codes()
+
+    with kvikio.defaults.set_http_status_codes([500]):
+        assert kvikio.defaults.http_status_codes() == [500]
+        kvikio.defaults.http_status_codes_reset([429, 500])
+        assert kvikio.defaults.http_status_codes() == [429, 500]
+    assert before == kvikio.defaults.http_status_codes()
```
Comment (bdice) [inline python/kvikio/tests/test_defaults.py:111]:
```suggestion
    assert kvikio.defaults.http_status_codes() == before
```

File: python/kvikio/tests/test_http_io.py [hunk 30]
```diff
@@ -18,6 +22,58 @@
...
+
+
+class HTTP500Handler(SimpleHTTPRequestHandler):
+    """
+    An HTTP handler that initially responds with a 503 before responding normally.
+
+    Parameters
+    ----------
+    error_counter : ErrorCounter
+        A class with a mutable `value` for the number of 500 errors that have
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:39]:
```suggestion
        A class with a mutable `value` for the number of 503 errors that have
```

File: python/kvikio/tests/test_http_io.py [hunk 31]
```diff
@@ -18,6 +22,58 @@
...
 
 
+class ErrorCounter:
+    # ThreadedHTTPServer creates a new handler per request.
+    # This lets us share some state between requests.
+    def __init__(self):
+        self.value = 0
+
+
+class HTTP500Handler(SimpleHTTPRequestHandler):
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:32]: This appears to be issuing 503, not 500.
```suggestion
class HTTP503Handler(SimpleHTTPRequestHandler):
```

File: python/kvikio/tests/test_http_io.py [hunk 32]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
             OverflowError, match="maybe the server doesn't support file ranges?"
         ):
             f.read(b, size=10, file_offset=10)
+
+
+def test_retry_http_500_ok(tmpdir, xp):
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:161]:
```suggestion
def test_retry_http_503_ok(tmpdir, xp):
```

File: python/kvikio/tests/test_http_io.py [hunk 33]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+    a = xp.arange(100, dtype="uint8")
+    a.tofile(tmpdir / "a")
+
+    with LocalHttpServer(
+        tmpdir,
+        max_lifetime=60,
+        handler=HTTP500Handler,
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:168]:
```suggestion
        handler=HTTP503Handler,
```

File: python/kvikio/tests/test_http_io.py [hunk 34]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+    ) as server:
+        http_server = server.url
+        b = xp.empty_like(a)
+        with kvikio.RemoteFile.open_http(f"{http_server}/a") as f:
+            assert f.nbytes() == a.nbytes
+            assert f"{http_server}/a" in str(f)
+            f.read(b)
+
+
+def test_retry_http_500_fails(tmpdir, xp):
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:179]:
```suggestion
def test_retry_http_503_fails(tmpdir, xp):
```

File: python/kvikio/tests/test_http_io.py [hunk 35]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+    with LocalHttpServer(
+        tmpdir,
+        max_lifetime=60,
+        handler=HTTP500Handler,
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:183]:
```suggestion
        handler=HTTP503Handler,
```

File: python/kvikio/tests/test_http_io.py [hunk 36]
```diff
@@ -100,3 +156,53 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+        with pytest.raises(RuntimeError, match="503"):
+            with kvikio.RemoteFile.open_http(f"{server.url}/a") as f:
+                f.read(b)
+
+
+def test_set_http_status_code(tmpdir, xp):
+    with LocalHttpServer(
+        tmpdir,
+        max_lifetime=60,
+        handler=HTTP500Handler,
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:199]:
```suggestion
        handler=HTTP503Handler,
```

**Review by bdice — COMMENTED** [review]
Overall this looks great. I have a few comments for small fixes. Once some of these are fixed, can you resolve open threads? Happy to re-review and approve then.

**Comment by TomAugspurger** [comment]
Thanks for the reviews and help everyone! All the comments should be addressed.

The branch is targeting 25.04 and CI is passing.

File: cpp/src/defaults.cpp [hunk 37]
```diff
@@ -200,4 +247,19 @@ void defaults::bounce_buffer_size_reset(std::size_t nbytes)
...
+{
+  if (attempts == 0) { throw std::invalid_argument("attempts must be a positive integer"); }
+  instance()->_http_max_attempts = attempts;
+}
+
+std::vector<int> const& defaults::http_status_codes() { return instance()->_http_status_codes; }
+
+void defaults::http_status_codes_reset(std::vector<int> status_codes)
+{
+  instance()->_http_status_codes = status_codes;
```
Comment (kingcrimsontianyu) [inline cpp/src/defaults.cpp:262]:
```suggestion
  instance()->_http_status_codes = std::move(status_codes);
```

File: cpp/src/defaults.cpp [hunk 38]
```diff
@@ -49,6 +50,28 @@ CompatMode parse_compat_mode_str(std::string_view compat_mode_str)
   return res;
 }
 
+std::vector<int> parse_http_status_codes(std::string_view env_var_name,
+                                         std::string const status_codes)
```
Comment (kingcrimsontianyu) [inline cpp/src/defaults.cpp:54]:
```suggestion
                                         std::string_view status_codes)
```

Comment (TomAugspurger) [reply cpp/src/defaults.cpp:54]: Looks like this one needs to be `std::string const`, otherwise there's a compile error at

```
$SRC_DIR/cpp/src/defaults.cpp: In function 'std::vector<int> kvikio::detail::parse_http_status_codes(std::string_view, std::string_view)':
```

I've changed it back to `std::string const` for now, but LMK if there's something better.

Comment (kingcrimsontianyu) [reply cpp/src/defaults.cpp:54]: Ah. Thanks for letting me know. I don't know much about the regex library, but on the surface, the fix is as follows for string_view:
```cpp
  // Before
  std::regex_match(status_codes, check_pattern)
  ...
  std::transform(std::sregex_iterator(status_codes.begin(), status_codes.end(), number_pattern),
                 std::sregex_iterator(),
                 std::back_inserter(ret),
                 [](std::smatch const& match) -> int { return std::stoi(match.str()); });

  // After
  std::regex_match(status_codes.data(), check_pattern)
  ...
  std::transform(std::regex_iterator(status_codes.begin(), status_codes.end(), number_pattern),
                 std::regex_iterator<std::string_view::const_iterator>(),
                 std::back_inserter(ret),
                 [](std::cmatch const& match) -> int { return std::atoi(match.str().c_str()); });
```
Alternatively, simply use the reference type as the function parameter to avoid the copy:
```cpp
std::vector<int> parse_http_status_codes(std::string_view env_var_name, std::string const& status_codes);
```

File: cpp/src/shim/libcurl.cpp [hunk 39]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
 {
-  // Perform the curl operation and check for errors.
-  CURLcode err = curl_easy_perform(handle());
-  if (err != CURLE_OK) {
-    std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
+  CURLcode err;
+  long http_code                            = 0;
+  int attempt_count                         = 1;
+  int baseDelay                             = 100;  // milliseconds
+  std::size_t http_max_attempts             = kvikio::defaults::http_max_attempts();
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:125]:
```suggestion
  auto http_max_attempts             = kvikio::defaults::http_max_attempts();
```

File: cpp/src/shim/libcurl.cpp [hunk 40]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+  std::vector<int> const& http_status_codes = kvikio::defaults::http_status_codes();
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:126]:
```suggestion
  auto& http_status_codes = kvikio::defaults::http_status_codes();
```

File: cpp/src/shim/libcurl.cpp [hunk 41]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+
+  while (attempt_count <= http_max_attempts) {
     std::stringstream ss;
-    ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
-    if (msg.empty()) {
-      ss << "(" << curl_easy_strerror(err) << ")";
+
+    CURLcode err = curl_easy_perform(handle());
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:131]:
```suggestion
    auto err = curl_easy_perform(handle());
```

File: cpp/src/shim/libcurl.cpp [hunk 42]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
 
 void CurlHandle::perform()
 {
-  // Perform the curl operation and check for errors.
-  CURLcode err = curl_easy_perform(handle());
-  if (err != CURLE_OK) {
-    std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
+  CURLcode err;
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:121]: It appears that `err` here is unused and is shadowed by its namesake in the while-loop.

Comment (kingcrimsontianyu) [reply cpp/src/shim/libcurl.cpp:121]: Suggest deletion.

File: cpp/src/shim/libcurl.cpp [hunk 43]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+  long http_code                            = 0;
+  int attempt_count                         = 1;
+  int baseDelay                             = 100;  // milliseconds
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:124]: Nit: use snake_case for consistency.

File: cpp/src/shim/libcurl.cpp [hunk 44]
```diff
@@ -116,19 +118,51 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        http_status_codes.end()) {
+      // Retry only if one of the specified status codes is returned
+      // TODO: Parse the Retry-After header, if it exists.
+      // TODO: configurable maximum wait.
+      ss << "HTTP " << http_code << std::endl;
+      if (attempt_count == http_max_attempts) {
+        ss << "Max attempts reached." << std::endl;
+        throw std::runtime_error(ss.str());
+      } else {
+        int backoffDelay = baseDelay * (1 << attempt_count);
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:145]: Nit: use snake_case for consistency.

File: cpp/src/defaults.cpp [hunk 45]
```diff
@@ -132,6 +166,19 @@ defaults::defaults()
     }
     _bounce_buffer_size = env;
   }
+  // Determine the default value of `http_max_attempts`
+  {
+    const ssize_t env = getenv_or("KVIKIO_HTTP_MAX_ATTEMPTS", 3);
+    if (env <= 0) {
```
Comment (kingcrimsontianyu) [inline cpp/src/defaults.cpp:172]: I think we could be a bit more defensive here against potential integer overflow in `CurlHandle::perform()`, where `1 << attempt_count` is performed. We could require that:
```cpp
    auto upperbound_exclusive = sizeof(int);
    if(env >= upperbound_exclusive) {
      throw std::invalid_argument("KVIKIO_HTTP_MAX_ATTEMPTS must be less than " + std::to_string(upperbound_exclusive));
    }
```
The same applies to `http_max_attempts_reset()`.

File: cpp/src/shim/libcurl.cpp [hunk 46]
```diff
@@ -116,19 +118,50 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+    auto err = curl_easy_perform(handle());
+    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);
+
+    // Check if we should retry based on HTTP status code
+    if (std::find(http_status_codes.begin(), http_status_codes.end(), http_code) !=
+        http_status_codes.end()) {
+      // Retry only if one of the specified status codes is returned
+      // TODO: Parse the Retry-After header, if it exists.
+      // TODO: configurable maximum wait.
+      ss << "HTTP " << http_code << std::endl;
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:139]: In the dev branch, the string stream is used to collect pieces of information to form an ensemble message for the exception. I'm wondering what is the intended action here. Don't we want to print the `http_code` to the standard output (`std::cout`)?

File: cpp/src/shim/libcurl.cpp [hunk 47]
```diff
@@ -116,19 +118,50 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+      if (attempt_count == http_max_attempts) {
+        ss << "Max attempts reached." << std::endl;
+        throw std::runtime_error(ss.str());
+      } else {
+        int backoff_delay = base_delay * (1 << attempt_count);
+        int delay         = std::max(1, backoff_delay);
+
+        attempt_count++;
+        ss << "Retrying. after=" << delay << " attempt=" << attempt_count
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:148]: Same as above. I think you meant to insert the data to the standard output rather than the string stream?

File: cpp/src/defaults.cpp (hunk 45 above)
Comment (TomAugspurger) [reply cpp/src/defaults.cpp:172]: Could you share what the potential problem is here (I'm new to C++). The comparison

```
  while (attempt_count <= http_max_attempts) {
 ```

might have an issue? `attempt_count` here is an `int` and `http_max_attempts` should be a `std::size_t`.

Should I make `attempt_count` a `std::size_t` as well?

File: cpp/src/shim/libcurl.cpp [hunk 48]
```diff
@@ -116,19 +118,50 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+    // Check if we should retry based on HTTP status code
+    if (std::find(http_status_codes.begin(), http_status_codes.end(), http_code) !=
+        http_status_codes.end()) {
+      // Retry only if one of the specified status codes is returned
+      // TODO: Parse the Retry-After header, if it exists.
+      // TODO: configurable maximum wait.
+      ss << "HTTP " << http_code << std::endl;
+      if (attempt_count == http_max_attempts) {
+        ss << "Max attempts reached." << std::endl;
+        throw std::runtime_error(ss.str());
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:142]:
```suggestion
        throw std::runtime_error("Max attempts reached.");
```

File: cpp/src/shim/libcurl.cpp [hunk 49]
```diff
@@ -116,19 +118,50 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        int delay         = std::max(1, backoff_delay);
+
+        attempt_count++;
+        ss << "Retrying. after=" << delay << " attempt=" << attempt_count
+           << " http_max_attempts=" << http_max_attempts << std::endl;
+        std::this_thread::sleep_for(std::chrono::milliseconds(delay));
+      }
+    } else if (err != CURLE_OK) {
+      std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
+      ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:154]: Move the string stream definition here:
```cpp
std::stringstream ss;
```

File: cpp/src/defaults.cpp (hunk 45 above)
Comment (kingcrimsontianyu) [reply cpp/src/defaults.cpp:172]: The comparison is fine. What is a bit risky is `1 << attempt_count` in `CurlHandle::perform()`. The number 1 has a type of `int` whose size is at least 16 bits (per C++ standard) and exactly 32 (on most systems). Say on a common system where `sizeof(int)` is indeed 32. If user sets `http_max_attempts` to a large value, then `attempt_count` may reach or exceed 32, and the bitwise left shift `1 << attempt_count` would have an "undefined behavior" (behavior that is solely determined by the specific compiler rather than the C++ standard). For example, `1 << 32` may give 0. So to mitigate this, we may cap `http_max_attempts` when its value was first parsed and set in KvikIO.

File: cpp/src/shim/libcurl.cpp (hunk 46 above)
Comment (kingcrimsontianyu) [reply cpp/src/shim/libcurl.cpp:139]: The C++ solution would be either implementing our own logger class, or using a good third-party logging library such as spdlog or glog. We don't have a dedicated logger yet in KvikIO, except this simplistic macro here that uses the standard error stream:

https://github.com/rapidsai/kvikio/blob/c38038e09f5f0687d880a751bcb125c6fb5f35fb/cpp/include/kvikio/error.hpp#L118

https://github.com/rapidsai/kvikio/blob/c38038e09f5f0687d880a751bcb125c6fb5f35fb/cpp/src/error.cpp#L25

For this PR, I think we can/should make do with `std::cout`, and we will ponder the logger design later. :smiley:

**Review by bdice — CHANGES_REQUESTED** [review]
I'd like for our choices of HTTP retry delay times to be more reasonable. (Apologies for missing this earlier.)

See: https://github.com/rapidsai/kvikio/pull/603/files#r1951116338

File: cpp/src/shim/libcurl.cpp (hunk 46 above)
Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp]: Thanks. I've gone with `std::cout` for now. I have a test at the python level asserting a few things about the output.

File: cpp/src/defaults.cpp (hunk 45 above)
Comment (bdice) [reply cpp/src/defaults.cpp:173]: Some additional reading on this topic:
- [This article](https://moath-omarsa.medium.com/http-requests-retry-strategy-11d7b0e02d6c) suggests 1s, 2s, 4s, up to a maximum of 20s between attempts.
- [AWS Simple Notification Service](https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html) uses 0s, 0s, 0s, 1s, 1s, 1s, 2s, 4s, 8s, 16s, 20s, 20s, 20s... (3 immediate retries, then two 1-second delays, then exponential backoff up to a max of 20 seconds)
- [This article](https://harish-bhattbhatt.medium.com/best-practices-for-retry-pattern-f29d47cd5117) suggests 1s, 2s, 5s
- The [AWS Architecture blog](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) and [Azure Architecture docs](https://learn.microsoft.com/en-us/azure/architecture/best-practices/transient-faults) both recommend adding jitter / randomization so that concurrent requests are dispersed in time as they are retried. I think this is also a good idea.

I think I would propose the following Python pseudocode, following from the AWS Architecture blog:
```python
base_delay = 500  # milliseconds
max_delay = 20000
delay = base_delay
for _ in range(retries):
    if try_http_request():
        break
    sleep(delay)
    delay = min(max_delay, random.uniform(base_delay, delay * 3)
```

File: cpp/src/shim/libcurl.cpp (hunk 46 above)
Comment (bdice) [reply cpp/src/shim/libcurl.cpp]: We have https://github.com/rapidsai/rapids-logger for logging. It wraps spdlog, which we do _very carefully_ to avoid exposing spdlog symbols in our libraries.

File: cpp/src/defaults.cpp (hunk 45 above)
Comment (TomAugspurger) [reply cpp/src/defaults.cpp:173]: Thanks, I (think) I've implemented that: a base delay of 500 ms and a maximum delay of 4s. Both of those parameters are currently hardcoded.

**Review by kingcrimsontianyu — APPROVED** [review]
Approved the C++ code. Thanks for the work. Great feature to have!

File: cpp/src/defaults.cpp [hunk 50]
```diff
@@ -132,6 +166,23 @@ defaults::defaults()
...
+  // Determine the default value of `http_max_attempts`
+  {
+    const ssize_t env         = getenv_or("KVIKIO_HTTP_MAX_ATTEMPTS", 3);
+    auto upperbound_exclusive = sizeof(int);
+    if (env <= 0) {
+      throw std::invalid_argument("KVIKIO_HTTP_MAX_ATTEMPTS has to be a positive integer");
+    } else if (env >= upperbound_exclusive) {
+      throw std::invalid_argument("KVIKIO_HTTP_MAX_ATTEMPTS must be less than " +
+                                  std::to_string(upperbound_exclusive));
+    }
```
Comment (bdice) [inline cpp/src/defaults.cpp:178]: We can probably remove the upper bound on attempts now.

File: cpp/src/shim/libcurl.cpp [hunk 51]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        std::stringstream ss;
+        ss << "kvikio http_max_attempts_reached. attempts=" << http_max_attempts
+           << " reason=" << http_code;
+        throw std::runtime_error(ss.str());
+      } else {
+        // backoff and retry again. With a base value of 500, we retry after
+        // 500ms, 1s, 2s, 4s, ...
+        int backoff_delay = base_delay * (1 << attempt_count);
+        // up to a maximum of `max_delay` seconds.
+        int delay = std::min(max_delay, backoff_delay);
```
Comment (bdice) [inline cpp/src/shim/libcurl.cpp:149]:
```suggestion
        auto const backoff_delay = base_delay * (1 << std::min(attempt_count, 4));
        // up to a maximum of `max_delay` seconds.
        auto const delay = std::min(max_delay, backoff_delay);
```

File: cpp/src/shim/libcurl.cpp [hunk 52]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
-  if (err != CURLE_OK) {
-    std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
-    std::stringstream ss;
-    ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
-    if (msg.empty()) {
-      ss << "(" << curl_easy_strerror(err) << ")";
+  long http_code          = 0;
+  int attempt_count       = 1;
+  int base_delay          = 500;   // milliseconds
+  int max_delay           = 4000;  // milliseconds
```
Comment (bdice) [inline cpp/src/shim/libcurl.cpp:125]: We should start from `attempt_count = 0` so that our first delay is 500ms (`500 * (1 << 0) = 500`).
```suggestion
  auto attempt_count        = 0;
  auto constexpr base_delay = 500;   // milliseconds
  auto constexpr max_delay  = 4000;  // milliseconds
```

File: cpp/src/shim/libcurl.cpp [hunk 53]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        // backoff and retry again. With a base value of 500, we retry after
+        // 500ms, 1s, 2s, 4s, ...
+        int backoff_delay = base_delay * (1 << attempt_count);
+        // up to a maximum of `max_delay` seconds.
+        int delay = std::min(max_delay, backoff_delay);
+
+        attempt_count++;
+        std::cout << "Retrying. reason=" << http_code << " after=" << delay
+                  << " attempt=" << attempt_count << " http_max_attempts=" << http_max_attempts
+                  << std::endl;
```
Comment (bdice) [inline cpp/src/shim/libcurl.cpp:154]: I'd use something human-readable here. We should indicate the unit of milliseconds.
```suggestion
        std::cout << "KvikIO: Retrying HTTP request. Got HTTP code " << http_code << " after " << delay
                  << "ms (attempt " << attempt_count << " of " << http_max_attempts
                  << ")." << std::endl;
```

File: cpp/src/shim/libcurl.cpp [hunk 54]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+    auto err = curl_easy_perform(handle());
+    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);
+
+    // Check if we should retry based on HTTP status code
+    if (std::find(http_status_codes.begin(), http_status_codes.end(), http_code) !=
+        http_status_codes.end()) {
+      // Retry only if one of the specified status codes is returned
+      // TODO: Parse the Retry-After header, if it exists.
+      // TODO: configurable maximum wait.
+      if (attempt_count == http_max_attempts) {
```
Comment (bdice) [inline cpp/src/shim/libcurl.cpp:139]: For safety:
```suggestion
      if (attempt_count >= http_max_attempts) {
```

File: cpp/src/shim/libcurl.cpp [hunk 55]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        std::stringstream ss;
+        ss << "kvikio http_max_attempts_reached. attempts=" << http_max_attempts
+           << " reason=" << http_code;
```
Comment (bdice) [inline cpp/src/shim/libcurl.cpp:142]: I'd use something more human-readable, like this:
```suggestion
        ss << "KvikIO: HTTP request reached maximum number of attempts (" << http_max_attempts << "). Got HTTP code " << http_code << "."
```

File: python/kvikio/tests/test_http_io.py [hunk 56]
```diff
@@ -100,3 +156,65 @@ def test_no_range_support(http_server, tmpdir, xp):
...
+        a.tofile(tmpdir / "a")
+        b = xp.empty_like(a)
+
+        with pytest.raises(RuntimeError) as m, kvikio.defaults.set_http_max_attempts(2):
+            with kvikio.RemoteFile.open_http(f"{server.url}/a") as f:
+                f.read(b)
+
+        assert m.match("kvikio http_max_attempts_reached")
+        assert m.match("attempts=2")
+        assert m.match("reason=503")
```
Comment (bdice) [inline python/kvikio/tests/test_http_io.py:196]: We would need to update these if we use human-readable errors suggested above.

**Review by bdice — COMMENTED** [review]
Some suggestions for the retry logic.

File: cpp/src/shim/libcurl.cpp (hunk 52 above)
Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp]: Thanks for catching that. I'll implement this by adjusting the backoff to be `base_delay * (1 << std::min(attempt_count - 1, 4));`, so subtracting 1 there, but keeping the initial attempt at 1. Then the loop logic can still be compared directly against the user-provided max_attempts.

File: cpp/src/shim/libcurl.cpp (hunk 46 above)
Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp]: Any objections to holding off on rapids-logger for this PR? It probably makes sense to make that change across the library.

File: cpp/src/defaults.cpp [hunk 57]
```diff
@@ -200,4 +247,19 @@ void defaults::bounce_buffer_size_reset(std::size_t nbytes)
   instance()->_bounce_buffer_size = nbytes;
 }
 
+std::size_t defaults::http_max_attempts() { return instance()->_http_max_attempts; }
```
Comment (kingcrimsontianyu) [inline cpp/src/defaults.cpp:250]: If we have decided to cap the delay time instead of the number of attempts, then we probably should change the new functions as well as update the documentation. Instead of:
```cpp
static std::size_t http_max_attempts();
void http_max_attempts_reset(std::size_t attempts);
```
We use something like:
```cpp
static std::size_t http_max_delay_ms();
void http_max_delay_ms_reset(std::size_t max_delay_ms);
```
What do you think?

File: cpp/src/shim/libcurl.cpp [hunk 58]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
 
 void CurlHandle::perform()
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:120]: I would suggest reorganizing the logic below to improve readability, such as separating handling of error code from http code, early breaking to reduce the indentation level.
```cpp
// Untested code. Please check!
void CurlHandle::perform()
{
  long http_code               = 0;
  auto constexpr base_delay_ms = 500;
  auto delay_multiplier        = 1;
  auto backoff_delay_ms        = 0;
  auto max_delay_ms            = kvikio::defaults::http_max_delay_ms();
  auto& http_status_codes      = kvikio::defaults::http_status_codes();
  auto attempt_count           = 0;

  while (true) {
    ++attempt_count;
    auto err = curl_easy_perform(handle());
    if (err != CURLE_OK) {
      std::string msg(_errbuf);  // We can do this because we always initialize `_errbuf` as empty.
      std::stringstream ss;
      ss << "curl_easy_perform() error near " << _source_file << ":" << _source_line;
      if (msg.empty()) {
        ss << "(" << curl_easy_strerror(err) << ")";
      } else {
        ss << "(" << msg << ")";
      }
      throw std::runtime_error(ss.str());
    }

    curl_easy_getinfo(handle(), CURLINFO_RESPONSE_CODE, &http_code);

    // Check if we should retry based on HTTP status code
    if (std::find(http_status_codes.begin(), http_status_codes.end(), http_code) ==
        http_status_codes.end()) {
      // No retry needed
      break;
    }

    // Retry only if one of the specified status codes is returned
    // TODO: Parse the Retry-After header, if it exists.
    // TODO: configurable maximum wait.

    // Current status report
    std::cout << "KvikIO: Retrying HTTP request. Got HTTP code " << http_code << " after "
              << backoff_delay_ms << "ms (attempt " << attempt_count << ")." << std::endl;

    // Prepare for the next attempt
    // backoff and retry again. With a base value of 500ms, we retry after
    // 500ms, 1s, 2s, 4s, ...
    backoff_delay_ms = base_delay_ms * delay_multiplier;
    delay_multiplier <<= 1;

    if (backoff_delay_ms > max_delay_ms) {
      std::stringstream ss;
      ss << "KvikIO: HTTP request reached maximum delay (" << max_delay_ms << "). Got HTTP code "
         << http_code << ".";
      throw std::runtime_error(ss.str());
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(backoff_delay_ms));
  }
}
```

File: cpp/src/shim/libcurl.cpp [hunk 59]
```diff
@@ -116,19 +119,55 @@ CURL* CurlHandle::handle() noexcept { return _handle.get(); }
...
+        throw std::runtime_error(ss.str());
+      } else {
+        // backoff and retry again. With a base value of 500ms, we retry after
+        // 500ms, 1s, 2s, 4s, ...
+        auto const backoff_delay = base_delay * (1 << std::min(attempt_count - 1, 4));
+        // up to a maximum of `max_delay` seconds.
+        auto const delay = std::min(max_delay, backoff_delay);
+
+        attempt_count++;
+        std::cout << "KvikIO: Retrying HTTP request. Got HTTP code " << http_code << " after "
```
Comment (kingcrimsontianyu) [inline cpp/src/shim/libcurl.cpp:152]: > Got HTTP code
Since this is the past tense. I think the first time it shows, the delay should be 0.

File: cpp/src/shim/libcurl.cpp (hunk 58 above)
Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp:120]: I was wondering whether a refactor like this made sense now. Let me take a look.

Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp:120]: https://github.com/rapidsai/kvikio/pull/603/commits/17d5fe083811bfa9593cb085e070a4ea93aa4c38 has something, if you're able to take another look. That's a bit of a compromise between the earlier setup and your suggestion:

- It does use the attempt_count in the `while` loop condition, instead of `while (true)`. But the case where we've exceeded our maximum attempts is moved out of the loop, and runs when we `break`
- I've added the early return for the case where things are OK, reducing the indentation level

File: cpp/src/shim/libcurl.cpp (hunk 59 above)
Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp]: Thanks. I think it's good to report that the previous request had some bad status code, and we'll sleep before the next attempt. So this now prints `KvikIO: Got HTTP code 503. Retrying after 500ms (attempt 2 of 2).`.

File: cpp/src/shim/libcurl.cpp (hunk 58 above)
Comment (kingcrimsontianyu) [reply cpp/src/shim/libcurl.cpp:120]: Yes. The changes look good to me! Please do test it a bit.

Side note: Hopefully we will improve the way of testing in the future through mocking (https://github.com/rapidsai/kvikio/issues/634).

Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp:120]: I think we have OK testing for this through the Python tests [here](https://github.com/rapidsai/kvikio/pull/603/files#diff-0faab0a9ab850b384efa891c56d96871bde6b639771d4234834cce9972c2ec30R190-R203).

That checks that we fail after two attempts, and the the expected message printed after the first attempt failed.

Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp:120]: There is an off by one error when the user sets the `set_http_max_attempts` to 1. Looking into it now.

Comment (TomAugspurger) [reply cpp/src/shim/libcurl.cpp:120]: Fixed in https://github.com/rapidsai/kvikio/pull/603/commits/85d4fd72b8c07eab40bc77c81f3c0e4541bf2576.

Now the messages are

```
KvikIO: Got HTTP code 503. Retrying after 500ms (attempt 1 of 2).  # on the first failure
KvikIO: HTTP request reached maximum number of attempts (2). Got HTTP code 503.  # on the second / final failure
```

**Comment by TomAugspurger** [comment]
@kingcrimsontianyu do you see anything obviously wrong with how I've structured the `parse_http_status_codes` function? I've tried to follow how you did `parse_compat_mode`, but my local build is failing with

```
$ build-all
[3/3] Linking CXX executable gtests/cpp_tests
FAILED: gtests/cpp_tests 
: && /home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include  -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/coder/.conda/envs/rapids/lib -Wl,-rpath-link,/home/coder/.conda/envs/rapids/lib -L/home/coder/.conda/envs/rapids/lib  -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs     -Wl,--dependency-file=tests/CMakeFiles/cpp_tests.dir/link.d tests/CMakeFiles/cpp_tests.dir/main.cpp.o tests/CMakeFiles/cpp_tests.dir/test_basic_io.cpp.o tests/CMakeFiles/cpp_tests.dir/test_defaults.cpp.o -o gtests/cpp_tests  -Wl,-rpath,/home/coder/kvikio/cpp/build/conda/cuda-12.8/release:  libkvikio.so  lib/libgmock.a  lib/libgtest.a  /home/coder/.conda/envs/rapids/lib/libcudart.so  -lpthread  -ldl  /home/coder/.conda/envs/rapids/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so && :
/home/coder/.conda/envs/rapids/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: tests/CMakeFiles/cpp_tests.dir/test_defaults.cpp.o: in function `Defaults_parse_http_status_codes_Test::TestBody()':
test_defaults.cpp:(.text._ZN37Defaults_parse_http_status_codes_Test8TestBodyEv+0x5ad): undefined reference to `kvikio::detail::parse_http_status_codes(std::basic_string_view<char, std::char_traits<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/coder/.conda/envs/rapids/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: test_defaults.cpp:(.text._ZN37Defaults_parse_http_status_codes_Test8TestBodyEv+0x9ba): undefined reference to `kvikio::detail::parse_http_status_codes(std::basic_string_view<char, std::char_traits<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by TomAugspurger** [comment]
CI is passing now.

**Review by madsbk — APPROVED** [review]
Looks great, thanks @TomAugspurger

**Comment by TomAugspurger** [comment]
Looking into the CI failure at https://github.com/rapidsai/kvikio/actions/runs/13444589202/job/37567619135?pr=603, with failures like

```
    def test_http_max_attempts():
>       before = kvikio.defaults.http_max_attempts()
E       AttributeError: module 'kvikio.defaults' has no attribute 'http_max_attempts'

```

Which would surprise me. It's almost like the code being tested was from `main` or something.

**Comment by TomAugspurger** [comment]
https://github.com/rapidsai/kvikio/actions/runs/13444589202/job/37567618823?pr=603#step:9:359  shows we got

```
kvikio                    25.04.00a25     cuda11_py310_250219_g77da587_25    rapidsai-nightly
```

Looking at https://anaconda.org/rapidsai-nightly/kvikio/files?page=2, I see a package with that name from 40 hours ago: https://anaconda.org/rapidsai-nightly/kvikio/25.04.00a25/download/linux-64/kvikio-25.04.00a25-cuda11_py310_250219_g77da587_25.conda. So it *does* seem like we were running an older version of the code, rather than this branch. I'll keep looking into why that might be.

**Comment by bdice** [comment]
@TomAugspurger I think CI is failing because the packages built by this PR pin to `nvcomp==4.2.0.11`. We are having an issue with the CI package cache not having up-to-date repodata, and we are attempting to debug that. Because it can't find `nvcomp==4.2.0.11`, it falls back to the packages on `rapidsai-nightly`.

**Comment by TomAugspurger** [comment]
> Think builds are failing here because you're genuinely missing an #include somewhere

Yep, I was. Fixed in https://github.com/rapidsai/kvikio/pull/603/commits/ae2ea11b24760259011492e2aa3b119e81b3bba8.

**Comment by jameslamb** [comment]
Ok yeah, on a re-run it failed in the same way as https://github.com/rapidsai/kvikio/pull/603#issuecomment-2672768018, and `nvcomp==4.2.0.11` was not pulled:

```text
nvcomp                    4.1.1.1              hf3d1f9a_0    conda-forge
```

https://github.com/rapidsai/kvikio/actions/runs/13466571002/job/37633868639?pr=603

So I think @bdice was right, and this caching thing was the problem.

File: python/kvikio/kvikio/defaults.py [hunk 60]
```diff
@@ -248,3 +248,99 @@ def set_bounce_buffer_size(nbytes: int):
...
+    ----------
+    attempts : int
+        The maximum number of attempts to try before raising an error.
+    """
+    kvikio._lib.defaults.http_max_attempts_reset(attempts)
+
+
+@contextlib.contextmanager
+def set_http_max_attempts(attempts: int):
+    """Context for resetting the maximum number of HTTP attempts.
```
[the remark this answers is not in the document]
Comment (TomAugspurger) [reply python/kvikio/kvikio/defaults.py:285]: I struggled with the names of these too. I like the way [donfig works](https://donfig.readthedocs.io/en/latest/configuration.html#directly-within-python), where the configuration is a Python object. Calling `.set` just sets it permenantly

```python
config.set({"http_max_attempts": 5})
```

while using that same expression as a context manager takes care of doing it globally:

```python
with config.set({"http_max_attempts": 5}): ...
```

And there's a `config.defaults` dictionary, which gives you the defaults if you needed to restore those for some reason.

---

For this PR, though, consistency with the reset of kvikio.defaults is probably most important. https://github.com/rapidsai/kvikio/issues/642 has an issue to track this.

**Comment by TomAugspurger** [comment]
Thanks for the reviews everyone!
