### PR TITLE
Explicitly manage TLS/SSL CA paths for remote I/O

### LINKED ISSUE #711: SSL error when loading remote file with pip installed kvikio
```
$ uvx --python=3.12 --with ipython --with kvikio-cu12 --prerelease allow --extra-index-url="https://pypi.anaconda.org/rapidsai-wheels-nightly/simple" ipython

In [1]: import kvikio

In [2]: kvikio.RemoteFile.open_http("https://github.com/opengeospatial/geoparquet/raw/refs/heads/main/test_data/data-linestring-encoding_native.parquet")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 kvikio.RemoteFile.open_http("https://github.com/opengeospatial/geoparquet/raw/refs/heads/main/test_data/data-linestring-encoding_native.parquet")

File /raid/toaugspurger/uv/archive-v0/t344VG65vhx2abIkWIQ0l/lib/python3.12/site-packages/kvikio/remote_file.py:69, in RemoteFile.open_http(cls, url, nbytes)
     53 @classmethod
     54 def open_http(
     55     cls,
     56     url: str,
     57     nbytes: Optional[int] = None,
     58 ) -> RemoteFile:
     59     """Open a http file.
     60
     61     Parameters
   (...)     67         for the file size.
     68     """
---> 69     return RemoteFile(_get_remote_module().RemoteFile.open_http(url, nbytes))

File remote_handle.pyx:97, in kvikio._lib.remote_handle.RemoteFile.open_http()

File remote_handle.pyx:86, in kvikio._lib.remote_handle.RemoteFile._from_endpoint()

RuntimeError: KvikIO failure at: /__w/kvikio/kvikio/cpp/src/shim/libcurl.cpp:176: curl_easy_perform() error (error setting certificate verify locations:  CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: /etc/ssl/certs)
```

Should users need to configure this manually?

### PR DESCRIPTION
**Pull request by kingcrimsontianyu**
## Background

`libcurl` have two path parameters related to the certificate authority (CA):

- `CURLOPT_CAINFO`, which specifies the CA bundle file path.
- `CURLOPT_CAPATH`, which specifies the directory of individual CA certificates with hash-based naming.

The default paths are determined at compile-time, which can cause issues if the Linux distributions where `libcurl` is built and run are different (e.g. on Rocky Linux vs Ubuntu as in our CI vs our lab system), and the certificates files are likely at different locations. This problem has been observed in KvikIO's wheel distribution, where HTTPS would fail with the message:

>error setting certificate verify locations:  CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: /etc/ssl/certs

## This PR

This PR addresses this problem. The certificate path is now explicitly searched for in the following order. The compile-time parameters, if any, are still used but treated with lowest priority.

- CA bundle file: Check env vars `CURL_CA_BUNDLE`, and `SSL_CERT_FILE`
- CA directory: Check env vars `SSL_CERT_DIR`
- CA bundle file: Search a set of distribution-specific locations for accessible bundle
- CA directory: Search a set of distribution-specific locations for accessible directory
- CA bundle file: Check if the compile-time path is given and accessible  
- CA directory: Check if the compile-time parameter is given and accessible

Depends on https://github.com/rapidsai/kvikio/pull/819 for the use of  `static` structured binding which is only available in C++ >=20
 
Closes #711

### CODE REVIEW

File: cpp/src/detail/tls.cpp [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+  // At least one path must exist
+  KVIKIO_EXPECT(ca_bundle_file.has_value() || ca_directory.has_value(),
+                "Failed to find accessible CA certificates.",
+                std::runtime_error);
+  return {ca_bundle_file, ca_directory};
+}
+
+void set_up_ca_paths(CurlHandle& curl)
+{
+  static auto const [ca_bundle_file, ca_directory] = get_ca_paths();
```
Comment (kingcrimsontianyu) [inline cpp/src/detail/tls.cpp:140]: `static` structured binding is not supported in C++17, and this helped to identify an oversight to be fixed by https://github.com/rapidsai/kvikio/pull/819.

**Review by madsbk — APPROVED** [review]
Nice work
