### PR TITLE
nvtx support macos

### LINKED ISSUE #471: Ambiguous  call to `nvtx3::payload::payload()` on macOS
```c++
/Users/jfaibussowit/soft/nv/legate.core.internal/arch-io/cmake_build/_deps/kvikio-src/cpp/include/kvikio/posix_io.hpp:276:3: error: call to constructor of 'nvtx3::payload' is ambiguous
  276 |   KVIKIO_NVTX_FUNC_RANGE("posix_host_read()", size);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jfaibussowit/soft/nv/legate.core.internal/arch-io/cmake_build/_deps/kvikio-src/cpp/include/kvikio/utils.hpp:309:18: note: expanded from macro 'KVIKIO_NVTX_FUNC_RANGE'
  308 |   GET_KVIKIO_NVTX_FUNC_RANGE_MACRO(                                  \
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  309 |     __VA_ARGS__, KVIKIO_NVTX_FUNC_RANGE_2, KVIKIO_NVTX_FUNC_RANGE_1) \
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  310 |   (__VA_ARGS__)
      |   ~~~~~~~~~~~~~
/Users/jfaibussowit/soft/nv/legate.core.internal/arch-io/cmake_build/_deps/kvikio-src/cpp/include/kvikio/utils.hpp:286:61: note: expanded from macro 'GET_KVIKIO_NVTX_FUNC_RANGE_MACRO'
  286 | #define GET_KVIKIO_NVTX_FUNC_RANGE_MACRO(_1, _2, NAME, ...) NAME
      |                                                             ^
/Users/jfaibussowit/soft/nv/legate.core.internal/arch-io/cmake_build/_deps/kvikio-src/cpp/include/kvikio/utils.hpp:283:12: note: expanded from macro 'KVIKIO_NVTX_FUNC_RANGE_2'
  283 |       msg, nvtx3::payload { val }                             \
      |            ^              ~~~~~~~
```
On macOS, `std::size_t` is `unsigned long`, which -- crucially -- is not `std::uint64_t` (`unsigned long long`).

Perhaps consider doing
```c++
KVIKIO_NVTX_FUNC_RANGE("posix_host_read()", std::uint64_t{size});
```
whenever `size` is `std::size_t`. Alternatively, the macro could be amended to do this automatically.

### PR DESCRIPTION
**Pull request by madsbk**
Closes #471

### CODE REVIEW

File: cpp/include/kvikio/utils.hpp [hunk 1]
```diff
@@ -69,6 +71,27 @@ inline constexpr std::size_t page_size = 4096;
   return reinterpret_cast<CUdeviceptr>(devPtr);
 }
 
+/**
+ * @brief Help function to convert value to 64 bit signed integer
+ */
+template <typename T, std::enable_if_t<std::is_integral_v<T>>* = nullptr>
+[[nodiscard]] std::int64_t convert_to_64bit(T value)
+{
+  if (value >= std::numeric_limits<std::int64_t>::max()) {
```
Comment (vuule) [inline cpp/include/kvikio/utils.hpp:80]: This function is probably not performance critical, but we could check if the type can overflow int64 with an `if constexpr`, so some instantiations don't even have the `max()` check.

**Review by vuule — APPROVED** [review]

File: cpp/include/kvikio/utils.hpp (hunk 1 above)
Comment (madsbk) [reply cpp/include/kvikio/utils.hpp]: good point, done

**Review by wence- — APPROVED** [review]
