### PR TITLE
Fix no-cuda build

### LINKED ISSUE #482: `nvtx3/nvtx3.hpp` file not found for CPU-only build.
```sh
path/to/kvikio/cpp/include/kvikio/utils.hpp:28:10: fatal error: 'nvtx3/nvtx3.hpp' file not found
   28 | #include <nvtx3/nvtx3.hpp>
      |          ^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by madsbk**
Closes #482

### CODE REVIEW

File: cpp/include/kvikio/utils.hpp [hunk 1]
```diff
@@ -308,6 +311,11 @@ struct libkvikio_domain {
       msg, nvtx3::payload { convert_to_64bit(val) }           \
     }                                                         \
   }
+#else
+#define KVIKIO_NVTX_FUNC_RANGE_2(msg, val) \
+  do {                                     \
+  } while (0)
+#endif
```
Comment (wence-) [inline cpp/include/kvikio/utils.hpp:318]: Could shovel this into the shim, but because it only appears here that seems like overkill.

**Review by wence- — APPROVED** [review]

File: cpp/include/kvikio/utils.hpp [hunk 2]
```diff
@@ -300,6 +302,7 @@ struct libkvikio_domain {
 
 // Macro overloads of KVIKIO_NVTX_FUNC_RANGE
 #define KVIKIO_NVTX_FUNC_RANGE_1() NVTX3_FUNC_RANGE_IN(libkvikio_domain)
+#ifdef KVIKIO_CUDA_FOUND
```
Comment (bdice) [inline cpp/include/kvikio/utils.hpp:305]: Why is this guard only needed for `KVIKIO_NVTX_FUNC_RANGE_2` but not `KVIKIO_NVTX_FUNC_RANGE_1`?

Comment (madsbk) [reply cpp/include/kvikio/utils.hpp]: Good catch, it worked because `BASIC_NO_CUDA_EXAMPLE` never materialize `KVIKIO_NVTX_FUNC_RANGE_1`. 
I have included all of them in the ifdef guard now: 168dd0c3f91449a16aadbf2cd84c1fcfbedfadc7

**Review by bdice — APPROVED** [review]
